# Generated by Django 5.0 on 2023-12-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='p_id',
            new_name='cart_id',
        ),
    ]
